// services/video_service.dart
import 'package:isl_application/utils/language_utils.dart';

// services/video_service.dart
class VideoService {
  static Map<String, String> englishWordToVideoPath = {
    'talk': 'assets/Talk.mp4',
    'television': 'assets/Television.mp4',
    'thank you': 'assets/Thank You.mp4',
    'thank': 'assets/Thank.mp4',
    'that': 'assets/That.mp4',
    'they': 'assets/They.mp4',
    'this': 'assets/This.mp4',
    'those': 'assets/Those.mp4',
    'time': 'assets/Time.mp4',
    'to': 'assets/To.mp4',
    'type': 'assets/Type.mp4',
    'u': 'assets/U.mp4',
    'us': 'assets/Us.mp4',
    'v': 'assets/V.mp4',
    'w': 'assets/W.mp4',
    'walk': 'assets/Walk.mp4',
    'wash': 'assets/Wash.mp4',
    'way': 'assets/Way.mp4',
    'we': 'assets/We.mp4',
    'welcome': 'assets/Welcome.mp4',
    'what': 'assets/What.mp4',
    'when': 'assets/When.mp4',
    'where': 'assets/Where.mp4',
    'which': 'assets/Which.mp4',
    'who': 'assets/Who.mp4',
    'whole': 'assets/Whole.mp4',
    'whose': 'assets/Whose.mp4',
    'why': 'assets/Why.mp4',
    'will': 'assets/Will.mp4',
    'with': 'assets/With.mp4',
    'without': 'assets/Without.mp4',
    'words': 'assets/Words.mp4',
    'work': 'assets/Work.mp4',
    'world': 'assets/World.mp4',
    'wrong': 'assets/Wrong.mp4',
    'x': 'assets/X.mp4',
    'y': 'assets/Y.mp4',
    'you': 'assets/You.mp4',
    'your': 'assets/Your.mp4',
    'yourself': 'assets/Yourself.mp4',
    'z': 'assets/Z.mp4',
    'zero': 'assets/0.mp4',
    'one': 'assets/1.mp4',
    'two': 'assets/2.mp4',
    'three': 'assets/3.mp4',
    'four': 'assets/4.mp4',
    'five': 'assets/5.mp4',
    'six': 'assets/6.mp4',
    'seven': 'assets/7.mp4',
    'eight': 'assets/8.mp4',
    'nine': 'assets/9.mp4',
    'a': 'assets/A.mp4',
    'after': 'assets/After.mp4',
    'again': 'assets/Again.mp4',
    'against': 'assets/Against.mp4',
    'age': 'assets/Age.mp4',
    'all': 'assets/All.mp4',
    'alone': 'assets/Alone.mp4',
    'also': 'assets/Also.mp4',
    'and': 'assets/And.mp4',
    'ask': 'assets/Ask.mp4',
    'at': 'assets/At.mp4',
    'b': 'assets/B.mp4',
    'be': 'assets/Be.mp4',
    'beautiful': 'assets/Beautiful.mp4',
    'before': 'assets/Before.mp4',
    'best': 'assets/Best.mp4',
    'better': 'assets/Better.mp4',
    'busy': 'assets/Busy.mp4',
    'but': 'assets/But.mp4',
    'bye': 'assets/Bye.mp4',
    'c': 'assets/C.mp4',
    'can': 'assets/Can.mp4',
    'cannot': 'assets/Cannot.mp4',
    'change': 'assets/Change.mp4',
    'college': 'assets/College.mp4',
    'come': 'assets/Come.mp4',
    'computer': 'assets/Computer.mp4',
    'd': 'assets/D.mp4',
    'day': 'assets/Day.mp4',
    'distance': 'assets/Distance.mp4',
    'do not': 'assets/Do Not.mp4',
    'do': 'assets/Do.mp4',
    'does not': 'assets/Does Not.mp4',
    'e': 'assets/E.mp4',
    'eat': 'assets/Eat.mp4',
    'engineer': 'assets/Engineer.mp4',
    'f': 'assets/F.mp4',
    'fight': 'assets/Fight.mp4',
    'finish': 'assets/Finish.mp4',
    'from': 'assets/From.mp4',
    'g': 'assets/G.mp4',
    'glitter': 'assets/Glitter.mp4',
    'go': 'assets/Go.mp4',
    'god': 'assets/God.mp4',
    'gold': 'assets/Gold.mp4',
    'good': 'assets/Good.mp4',
    'great': 'assets/Great.mp4',
    'h': 'assets/H.mp4',
    'hand': 'assets/Hand.mp4',
    'hands': 'assets/Hands.mp4',
    'happy': 'assets/Happy.mp4',
    'hello': 'assets/Hello.mp4',
    'help': 'assets/Help.mp4',
    'her': 'assets/Her.mp4',
    'here': 'assets/Here.mp4',
    'his': 'assets/His.mp4',
    'home': 'assets/Home.mp4',
    'homepage': 'assets/Homepage.mp4',
    'how': 'assets/How.mp4',
    'i': 'assets/I.mp4',
    'invent': 'assets/Invent.mp4',
    'it': 'assets/It.mp4',
    'j': 'assets/J.mp4',
    'k': 'assets/K.mp4',
    'keep': 'assets/Keep.mp4',
    'l': 'assets/L.mp4',
    'language': 'assets/Language.mp4',
    'laugh': 'assets/Laugh.mp4',
    'learn': 'assets/Learn.mp4',
    'm': 'assets/M.mp4',
    'me': 'assets/Me.mp4',
    'more': 'assets/More.mp4',
    'my': 'assets/My.mp4',
    'n': 'assets/N.mp4',
    'name': 'assets/Name.mp4',
    'next': 'assets/Next.mp4',
    'not': 'assets/Not.mp4',
    'now': 'assets/Now.mp4',
    'o': 'assets/O.mp4',
    'of': 'assets/Of.mp4',
    'on': 'assets/On.mp4',
    'our': 'assets/Our.mp4',
    'out': 'assets/Out.mp4',
    'p': 'assets/P.mp4',
    'pretty': 'assets/Pretty.mp4',
    'q': 'assets/Q.mp4',
    'r': 'assets/R.mp4',
    'right': 'assets/Right.mp4',
    's': 'assets/S.mp4',
    'sad': 'assets/Sad.mp4',
    'safe': 'assets/Safe.mp4',
    'see': 'assets/See.mp4',
    'self': 'assets/Self.mp4',
    'sign': 'assets/Sign.mp4',
    'sing': 'assets/Sing.mp4',
    'so': 'assets/So.mp4',
    'sound': 'assets/Sound.mp4',
    'stay': 'assets/Stay.mp4',
    'study': 'assets/Study.mp4',
    't': 'assets/T.mp4',
  };

  static Map<String, String> hindiWordToVideoPath = {
    'बात': 'assets/Talk.mp4',
    'टेलीविजन': 'assets/Television.mp4',
    'धन्यवाद': 'assets/Thank You.mp4',
    'धन्यवाद': 'assets/Thank.mp4',
    'वह': 'assets/That.mp4',
    'वे': 'assets/They.mp4',
    'यह': 'assets/This.mp4',
    'वे': 'assets/Those.mp4',
    'समय': 'assets/Time.mp4',
    'को': 'assets/To.mp4',
    'प्रकार': 'assets/Type.mp4',
    'यू': 'assets/U.mp4',
    'हम': 'assets/Us.mp4',
    'वी': 'assets/V.mp4',
    'डब्ल्यू': 'assets/W.mp4',
    'चलना': 'assets/Walk.mp4',
    'धोना': 'assets/Wash.mp4',
    'रास्ता': 'assets/Way.mp4',
    'हम': 'assets/We.mp4',
    'स्वागत': 'assets/Welcome.mp4',
    'क्या': 'assets/What.mp4',
    'कब': 'assets/When.mp4',
    'कहाँ': 'assets/Where.mp4',
    'कौन सा': 'assets/Which.mp4',
    'कौन': 'assets/Who.mp4',
    'पूरा': 'assets/Whole.mp4',
    'जिसका': 'assets/Whose.mp4',
    'क्यों': 'assets/Why.mp4',
    'होगा': 'assets/Will.mp4',
    'के साथ': 'assets/With.mp4',
    'बिना': 'assets/Without.mp4',
    'शब्द': 'assets/Words.mp4',
    'काम': 'assets/Work.mp4',
    'दुनिया': 'assets/World.mp4',
    'गलत': 'assets/Wrong.mp4',
    'एक्स': 'assets/X.mp4',
    'वाई': 'assets/Y.mp4',
    'तुम': 'assets/You.mp4',
    'तुम्हारा': 'assets/Your.mp4',
    'अपने आप को': 'assets/Yourself.mp4',
    'जेड': 'assets/Z.mp4',
    'शून्य': 'assets/0.mp4',
    'एक': 'assets/1.mp4',
    'दो': 'assets/2.mp4',
    'तीन': 'assets/3.mp4',
    'चार': 'assets/4.mp4',
    'पाँच': 'assets/5.mp4',
    'छह': 'assets/6.mp4',
    'सात': 'assets/7.mp4',
    'आठ': 'assets/8.mp4',
    'नौ': 'assets/9.mp4',
    'ए': 'assets/A.mp4',
    'बाद में': 'assets/After.mp4',
    'फिर से': 'assets/Again.mp4',
    'के खिलाफ': 'assets/Against.mp4',
    'उम्र': 'assets/Age.mp4',
    'सभी': 'assets/All.mp4',
    'अकेला': 'assets/Alone.mp4',
    'भी': 'assets/Also.mp4',
    'एवं': 'assets/And.mp4',
    'पूछना': 'assets/Ask.mp4',
    'पर': 'assets/At.mp4',
    'बी': 'assets/B.mp4',
    'होना': 'assets/Be.mp4',
    'सुंदर': 'assets/Beautiful.mp4',
    'पहले': 'assets/Before.mp4',
    'सर्वोत्तम': 'assets/Best.mp4',
    'बेहतर': 'assets/Better.mp4',
    'व्यस्त': 'assets/Busy.mp4',
    'लेकिन': 'assets/But.mp4',
    'अलविदा': 'assets/Bye.mp4',
    'सी': 'assets/C.mp4',
    'कर सकते हैं': 'assets/Can.mp4',
    'नहीं कर सकते': 'assets/Cannot.mp4',
    'परिवर्तन': 'assets/Change.mp4',
    'कॉलेज': 'assets/College.mp4',
    'आना': 'assets/Come.mp4',
    'कंप्यूटर': 'assets/Computer.mp4',
    'डी': 'assets/D.mp4',
    'दिन': 'assets/Day.mp4',
    'दूरी': 'assets/Distance.mp4',
    'नहीं करना': 'assets/Do Not.mp4',
    'करना': 'assets/Do.mp4',
    'नहीं करता': 'assets/Does Not.mp4',
    'ई': 'assets/E.mp4',
    'खाना': 'assets/Eat.mp4',
    'इंजीनियर': 'assets/Engineer.mp4',
    'एफ': 'assets/F.mp4',
    'लड़ाई': 'assets/Fight.mp4',
    'समाप्त': 'assets/Finish.mp4',
    'से': 'assets/From.mp4',
    'जी': 'assets/G.mp4',
    'चमक': 'assets/Glitter.mp4',
    'जाना': 'assets/Go.mp4',
    'ईश्वर': 'assets/God.mp4',
    'सोना': 'assets/Gold.mp4',
    'अच्छा': 'assets/Good.mp4',
    'महान': 'assets/Great.mp4',
    'एच': 'assets/H.mp4',
    'हाथ': 'assets/Hand.mp4',
    'हाथ': 'assets/Hands.mp4',
    'खुश': 'assets/Happy.mp4',
    'हेलो': 'assets/Hello.mp4',
    'मदद': 'assets/Help.mp4',
    'उसकी': 'assets/Her.mp4',
    'यहाँ': 'assets/Here.mp4',
    'उसका': 'assets/His.mp4',
    'घर': 'assets/Home.mp4',
    'होमपेज': 'assets/Homepage.mp4',
    'कैसे': 'assets/How.mp4',
    'मैं': 'assets/I.mp4',
    'आविष्कार': 'assets/Invent.mp4',
    'यह': 'assets/It.mp4',
    'जे': 'assets/J.mp4',
    'के': 'assets/K.mp4',
    'रखना': 'assets/Keep.mp4',
    'एल': 'assets/L.mp4',
    'भाषा': 'assets/Language.mp4',
    'हंसी': 'assets/Laugh.mp4',
    'सीखना': 'assets/Learn.mp4',
    'एम': 'assets/M.mp4',
    'मैं': 'assets/Me.mp4',
    'अधिक': 'assets/More.mp4',
    'मेरा': 'assets/My.mp4',
    'एन': 'assets/N.mp4',
    'नाम': 'assets/Name.mp4',
    'अगला': 'assets/Next.mp4',
    'नहीं': 'assets/Not.mp4',
    'अब': 'assets/Now.mp4',
    'ओ': 'assets/O.mp4',
    'का': 'assets/Of.mp4',
    'पर': 'assets/On.mp4',
    'हमारा': 'assets/Our.mp4',
    'बाहर': 'assets/Out.mp4',
    'पी': 'assets/P.mp4',
    'सुंदर': 'assets/Pretty.mp4',
    'क्यू': 'assets/Q.mp4',
    'आर': 'assets/R.mp4',
    'सही': 'assets/Right.mp4',
    'एस': 'assets/S.mp4',
    'उदास': 'assets/Sad.mp4',
    'सुरक्षित': 'assets/Safe.mp4',
    'देखना': 'assets/See.mp4',
    'स्वयं': 'assets/Self.mp4',
    'साइन': 'assets/Sign.mp4',
    'गाना': 'assets/Sing.mp4',
    'तो': 'assets/So.mp4',
    'ध्वनि': 'assets/Sound.mp4',
    'रहना': 'assets/Stay.mp4',
    'अध्ययन': 'assets/Study.mp4',
    'टी': 'assets/T.mp4',
  };

  static String? getVideoPathForWord(String word, AppLanguage language) {
    print('Debug: Looking for video for word: ${word.toLowerCase()}');
    final wordMap = language == AppLanguage.english
        ? englishWordToVideoPath
        : hindiWordToVideoPath;

    final videoPath = wordMap[word.toLowerCase()];
    print('Debug: Found video path: $videoPath');
    return videoPath;
  }

  static List<String> processText(String text, AppLanguage language) {
    print('Debug: Processing text: $text');
    final words = text.toLowerCase().split(' ');
    print('Debug: Split words: $words');

    final wordMap = language == AppLanguage.english
        ? englishWordToVideoPath
        : hindiWordToVideoPath;

    final matchedWords =
        words.where((word) => wordMap.containsKey(word)).toList();
    print('Debug: Matched words: $matchedWords');
    return matchedWords;
  }
}
